name: Entregables

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Paso 1 Checkout repo
        uses: actions/checkout@v4

      - name: Paso 2 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Paso 3 - crea entorno virtual
        run: python -m venv venv

      - name: Paso 4 - actualizar pip (en entorno virtual)
        run: venv\Scripts\pip install --upgrade pip

      - name: Paso 5 - instalar dependencias (en entorno virtual)
        run: venv\Scripts\pip install -e .

      - name: Paso 6 - Ejecutar Script de main (en entorno virtual)
        run: venv\Scripts\python src/proyecto_integrado_V/main.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: proyecto integrado
          commit_user_name: Sergio Bustos Jimenez [GitHub Actions]
          commit_user_email: sergio.bustos@est.iudigital.edu.co
          commit_author: sergio.bustos@est.iudigital.edu.co <sergio.bustos@est.iudigital.edu.co>
